# Generated by Django 5.0.6 on 2024-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[("APPROVED", "Approved"), ("DISAPPROVED", "Disapproved")],
                max_length=15,
                null=True,
            ),
        ),
    ]
