# Generated by Django 5.0.6 on 2024-06-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_assignmentanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentanswer",
            name="module",
        ),
        migrations.AddField(
            model_name="assignmentanswer",
            name="assignment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.assignment",
            ),
            preserve_default=False,
        ),
    ]
