# Generated by Django 5.0.6 on 2024-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paystack_authorization_code",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
